import os
from flask_mail import Mail, Message

mail = Mail()

def init_mail(app):
    app.config['MAIL_SERVER'] = 'smtp.gmail.com'
    app.config['MAIL_PORT'] = 587
    app.config['MAIL_USE_TLS'] = True
    app.config['MAIL_USERNAME'] = os.getenv("MAIL_USERNAME")
    app.config['MAIL_PASSWORD'] = os.getenv("MAIL_PASSWORD")
    app.config['MAIL_DEFAULT_SENDER'] = os.getenv("MAIL_USERNAME")
    
    mail.init_app(app)

def send_report_email(to_email: str, patient_name: str, stage: str, confidence: str, pdf_bytes: bytes):
    try:
        msg = Message(
            subject=f"NeuroScan AI Report — {patient_name}",
            recipients=[to_email]
        )
        msg.body = (
            f"Hello,\n\n"
            f"Please find attached the NeuroScan AI Report for {patient_name}.\n\n"
            f"Detected Stage: {stage}\n"
            f"Confidence: {confidence}%\n\n"
            f"Note: This report is generated by an AI system for educational/research purposes. "
            f"Always verify with clinical evaluation.\n\n"
            f"Regards,\nNeuroScan AI System"
        )
        msg.attach(
            filename=f"NeuroScan_Report_{patient_name.replace(' ', '_')}.pdf",
            content_type="application/pdf",
            data=pdf_bytes
        )
        mail.send(msg)
        return True, "Email sent successfully!"
    except Exception as e:
        return False, str(e)
